### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by FrankGod111** [zhoubohan0/STG-Transformer#3]
When I encountered the following error, I have tried the solution online, how to solve this?
Traceback (most recent call last):
  File ".\dataset\process_Dopamine.py", line 16, in <module>
    env = gym.make(f'{env_id}', stack=True)  # -v{0, 1, 2, 3, 4} for datasets with the other random seeds
  File "C:\Users\FrankGod\.conda\envs\STGGPU\lib\site-packages\gym\envs\registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "C:\Users\FrankGod\.conda\envs\STGGPU\lib\site-packages\gym\envs\registration.py", line 105, in make
    spec = self.spec(path)
  File "C:\Users\FrankGod\.conda\envs\STGGPU\lib\site-packages\gym\envs\registration.py", line 167, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: breakout-epoch-50-v0

**Comment by marleynika03** [comment]
Hi, could you provide the complete code?
